services:
  postgres_store:
    container_name: postgres_store
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_store:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin_storage:
    container_name: pgadmin_storage
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@mail.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin3:/var/lib/pgadmin3
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  keycloak:
    container_name: keycloak-ms2
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    networks:
      - spring
      - postgres
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: denis
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - "start-dev"
  minio:
    image: 'minio/minio:latest'
    container_name: my_minio
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"

  storage:
    image: denisproduction/storage:latest
    container_name: storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres_store
    ports:
      - "8082:8082"
    networks:
      - postgres
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres_store:
  pgadmin3:
  keycloak_data:
    driver: local
  minio:
    driver: local