services:
  postgres:
    build:
      context: ./postgres
    image: postgres-superset:latest
    container_name: superset_postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: superset
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
    networks:
      - supernet
      - airflow
    ports:
      - "5444:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    healthcheck:
      test: ["CMD", "pg_isready -U superset -d superset"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-superset:latest
    container_name: superset
    env_file:
      - .env
    ports:
      - "8088:8088"
    environment:
      DATABASE_URL: postgresql+psycopg2://superset:password@superset_postgres:5432/superset
      SUPERSET_SECRET_KEY: "this_is_a_secret_key"
      REDIS_URL: "redis://redis:6379/0"
      SUPERSET_ADMIN_LOGIN: "${SUPERSET_ADMIN_LOGIN}"
      SUPERSET_ADMIN_PASSWORD: "${SUPERSET_ADMIN_PASSWORD}"
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - postgres
    networks:
      - supernet
    entrypoint: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_ADMIN_LOGIN} --password ${SUPERSET_ADMIN_PASSWORD} --firstname Admin --lastname User --email admin@example.com &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

networks:
  supernet:
    driver: bridge
  airflow:
    external: true

volumes:
  superset_home:
  postgres-volume: