# Set individual file size
spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    url: jdbc:postgresql://postgres_store:5432/warehouse
    username: denis
    password: password

    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
      #      ddl-auto: create-drop
    show-sql: false


#minio file server configuration
s3:
  url: http://localhost:9000
  accessKey: HeaIFfjGVHBS4jGB3YYr
  secretKey: C9MbND36i8s2TlUJ4HAhPrc8ATuBnxizPfILui2R
  bucketName: rawdata

server:
  port: 8082